# -*- coding: utf-8 -*-
"""social media automation agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1seW48bojVDP5b3ZV-413iV-DjLRrL47w
"""

import google.generativeai as genai
from dataclasses import dataclass
from langgraph.graph import StateGraph, END
import os
import pickle

import google.generativeai as genai

GEMINI_API_KEY = "AIzaSyBtSTk2YSGVkdI_gUij8i4llXygwLe_Dtw"
genai.configure(api_key=GEMINI_API_KEY)

def call_llm(prompt: str) -> str:
    model = genai.GenerativeModel("gemini-2.5-flash")
    response = model.generate_content(prompt, generation_config={"temperature":0.5})
    return response.text

def generate_post(topic, platform):
    prompt = f"Generate an engaging social media post for {platform} about: {topic}"
    return {"post": call_llm(prompt)}

def generate_hashtags(post_text):
    prompt = f"Generate relevant hashtags for this post:\n{post_text}"
    return {"hashtags": call_llm(prompt)}

def reply_to_comment(comment):
    prompt = f"Write a polite and engaging reply to this comment:\n{comment}"
    return {"reply": call_llm(prompt)}

# LangGraph state
@dataclass
class SocialMediaState:
    topic: str = ""
    platform: str = ""
    post: str = ""
    hashtags: str = ""
    comment: str = ""
    reply: str = ""

# Build LangGraph workflow
def build_social_graph():
    graph = StateGraph(SocialMediaState)

    graph.add_node("generate_post", lambda s: generate_post(s.topic, s.platform))
    graph.add_node("generate_hashtags", lambda s: generate_hashtags(s.post))
    graph.add_node("reply_comment", lambda s: reply_to_comment(s.comment))

    graph.set_entry_point("generate_post")
    graph.add_edge("generate_post", "generate_hashtags")
    graph.add_edge("generate_hashtags", "reply_comment")
    graph.add_edge("reply_comment", END)

    return graph.compile()

# Instantiate agent
social_agent = build_social_graph()

# Run function
def run_social_agent(topic, platform="Twitter", comment=""):
    state = SocialMediaState(topic=topic, platform=platform, comment=comment)
    result = social_agent.invoke(state)
    return {
        "post": result.get("post"),
        "hashtags": result.get("hashtags"),
        "reply": result.get("reply")
    }

output = run_social_agent(
    topic="AI tools for small businesses",
    platform="LinkedIn",
    comment="This is very insightful!"
)
print(output)

# List of sample social media tasks
questions = [
    {"topic": "AI tools for small businesses", "platform": "LinkedIn", "comment": "Very insightful!"},
    {"topic": "Sustainable fashion trends", "platform": "Instagram", "comment": "Love this!"},
    {"topic": "Top productivity apps in 2025", "platform": "Twitter", "comment": "Great suggestions!"},
    {"topic": "Healthy meal prep tips", "platform": "Facebook", "comment": "Thanks for sharing!"},
    {"topic": "Latest advancements in AI agents", "platform": "LinkedIn", "comment": "Impressive insights!"},
    {"topic": "How to grow your YouTube channel", "platform": "YouTube", "comment": "Amazing tips!"},
    {"topic": "Top 10 coding best practices", "platform": "Twitter", "comment": "Very helpful!"},
    {"topic": "Remote work productivity hacks", "platform": "LinkedIn", "comment": "Useful info!"},
    {"topic": "Eco-friendly travel destinations", "platform": "Instagram", "comment": "Great ideas!"},
    {"topic": "Tips for beginner photographers", "platform": "Facebook", "comment": "Nice suggestions!"}
]

# Loop over each prompt and run the agent
for q in questions:
    print(f"\n=== Topic: {q['topic']} | Platform: {q['platform']} ===\n")
    output = run_social_agent(topic=q['topic'], platform=q['platform'], comment=q['comment'])
    print("Generated Post:\n", output['post'])
    print("Hashtags:\n", output['hashtags'])
    print("Reply to Comment:\n", output['reply'])
    print("\n" + "-"*80)

def save_agent(filepath="saved_state/social_agent.pkl"):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "wb") as f:
        pickle.dump(social_agent, f)

def load_agent(filepath="saved_state/social_agent.pkl"):
    with open(filepath, "rb") as f:
        return pickle.load(f)